#!/usr/bin/env bats
# Configuration syntax validation tests
#
# These tests verify that the configuration files generated by each
# protocol module have valid syntax and required structure — catching
# issues that would prevent services from starting on a real VPS.

load test_helper

setup_file() {
    export TMP_DIR=$(mktemp -d)
    export PROJECT_ROOT="$(cd "$(dirname "${BATS_TEST_FILENAME}")" && pwd)/.."

    # --- Xray Reality fixture ---
    XRAY_FIXTURE_DIR="$TMP_DIR/xray-reality"
    mkdir -p "$XRAY_FIXTURE_DIR"
    cat > "$XRAY_FIXTURE_DIR/config.json" <<'JSON'
{
    "inbounds": [
        {
            "listen": "0.0.0.0",
            "port": 8443,
            "protocol": "vless",
            "settings": {
                "clients": [
                    {
                        "id": "11111111-1111-4111-8111-111111111111",
                        "flow": "xtls-rprx-vision"
                    }
                ],
                "decryption": "none"
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "serverNames": ["www.example.com"],
                    "shortIds": ["aabbccddeeff0011"]
                }
            }
        }
    ]
}
JSON

    # --- Shadowsocks fixture ---
    SS_FIXTURE_DIR="$TMP_DIR/shadowsocks"
    mkdir -p "$SS_FIXTURE_DIR"
    cat > "$SS_FIXTURE_DIR/config.json" <<'JSON'
{
    "servers": [
        {
            "server": "0.0.0.0",
            "server_port": 8388,
            "password": "ss-password-fixture",
            "method": "2022-blake3-aes-256-gcm"
        }
    ]
}
JSON

    # --- WireGuard fixture ---
    WG_FIXTURE_DIR="$TMP_DIR/wireguard"
    mkdir -p "$WG_FIXTURE_DIR/clients"
    cat > "$WG_FIXTURE_DIR/config.conf" <<'CONF'
[Interface]
PrivateKey = eM9vX/Gf8H7yT5tQ3wR1pL6kS2nA4bC8dF0jK7lM9xV=
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = fH2jK8lM1nB4vC7xZ9qW3rT5yU6iO0pA=
AllowedIPs = 10.0.0.2/32
CONF

    cat > "$WG_FIXTURE_DIR/clients/client1.conf" <<'CONF'
[Interface]
PrivateKey = client-private+key=
Address = 10.0.0.2/32
DNS = 1.1.1.1, 8.8.8.8
MTU = 1360

[Peer]
PublicKey = server-public+key=
PresharedKey = pre-shared+key=
Endpoint = 203.0.113.10:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
CONF

    # --- Hysteria2 fixture ---
    HY2_FIXTURE_DIR="$TMP_DIR/hysteria2"
    mkdir -p "$HY2_FIXTURE_DIR"
    cat > "$HY2_FIXTURE_DIR/config.yaml" <<'YAML'
listen: :443

tls:
  cert: /etc/ssl/easynet-edge/fullchain.crt
  key: /etc/ssl/easynet-edge/private.key

auth:
  type: password
  password: hysteria-password-fixture

masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com/
    rewriteHost: true

obfs:
  type: salamander
  salamander:
    password: hysteria-obfs-fixture
YAML

    # --- Edge Nginx fixtures (generated by write_edge_http_site / write_edge_https_site) ---
    EDGE_WEB_ROOT="$TMP_DIR/nginx"
    mkdir -p "$EDGE_WEB_ROOT"
    # Export for use in tests
    export XRAY_FIXTURE_DIR SS_FIXTURE_DIR WG_FIXTURE_DIR HY2_FIXTURE_DIR EDGE_WEB_ROOT
}

teardown_file() {
    rm -rf "$TMP_DIR"
}

# ============================================================
# Xray Reality config validation
# ============================================================

@test "Xray Reality config.json is valid JSON" {
    jq . "$XRAY_FIXTURE_DIR/config.json" >/dev/null
}

@test "Xray Reality config has required listen directive" {
    local listen
    listen=$(jq -r '.inbounds[0].listen // empty' "$XRAY_FIXTURE_DIR/config.json")
    [ -n "$listen" ]
}

@test "Xray Reality config has valid port" {
    local port
    port=$(jq -r '.inbounds[0].port // 0' "$XRAY_FIXTURE_DIR/config.json")
    [ "$port" -ge 1 ] && [ "$port" -le 65535 ]
}

@test "Xray Reality config has valid protocol (vless)" {
    local proto
    proto=$(jq -r '.inbounds[0].protocol // empty' "$XRAY_FIXTURE_DIR/config.json")
    [ "$proto" = "vless" ]
}

@test "Xray Reality config has streamSettings with reality security" {
    local security
    security=$(jq -r '.inbounds[0].streamSettings.security // empty' "$XRAY_FIXTURE_DIR/config.json")
    [ "$security" = "reality" ]
}

@test "Xray Reality config has shortId for client access" {
    local short_id
    short_id=$(jq -r '.inbounds[0].streamSettings.realitySettings.shortIds[0] // empty' "$XRAY_FIXTURE_DIR/config.json")
    [ -n "$short_id" ]
}

# ============================================================
# Shadowsocks config validation
# ============================================================

@test "Shadowsocks config.json is valid JSON" {
    jq . "$SS_FIXTURE_DIR/config.json" >/dev/null
}

@test "Shadowsocks config has required server port" {
    local port
    port=$(jq -r '.servers[0].server_port // 0' "$SS_FIXTURE_DIR/config.json")
    [ "$port" -ge 1 ] && [ "$port" -le 65535 ]
}

@test "Shadowsocks config has a password" {
    local pwd
    pwd=$(jq -r '.servers[0].password // empty' "$SS_FIXTURE_DIR/config.json")
    [ -n "$pwd" ]
}

@test "Shadowsocks config has valid encryption method" {
    local method
    method=$(jq -r '.servers[0].method // empty' "$SS_FIXTURE_DIR/config.json")
    [ -n "$method" ]
}

# ============================================================
# WireGuard config validation
# ============================================================

@test "WireGuard server config has [Interface] section" {
    grep -q '^\[Interface\]' "$WG_FIXTURE_DIR/config.conf"
}

@test "WireGuard server config has PrivateKey" {
    grep -qE '^PrivateKey\s*=\s*[A-Za-z0-9+/]{40,}={0,2}$' "$WG_FIXTURE_DIR/config.conf"
}

@test "WireGuard server config has ListenPort" {
    grep -qE '^ListenPort\s*=\s*[0-9]+$' "$WG_FIXTURE_DIR/config.conf"
}

@test "WireGuard client config has [Peer] section with Endpoint" {
    grep -q '^\[Peer\]' "$WG_FIXTURE_DIR/clients/client1.conf"
    grep -qE '^Endpoint\s*=\s*[0-9.]+:[0-9]+$' "$WG_FIXTURE_DIR/clients/client1.conf"
}

@test "WireGuard client config has AllowedIPs for full tunnel" {
    grep -qE '^AllowedIPs\s*=\s*0\.0\.0\.0/0' "$WG_FIXTURE_DIR/clients/client1.conf"
}

@test "WireGuard client config has valid DNS servers" {
    grep -qE '^DNS\s*=\s*[0-9.]+,\s*[0-9.]+' "$WG_FIXTURE_DIR/clients/client1.conf"
}

# ============================================================
# Hysteria2 config validation
# ============================================================

@test "Hysteria2 config has listen port directive" {
    grep -qE '^listen:\s*:[0-9]+$' "$HY2_FIXTURE_DIR/config.yaml"
}

@test "Hysteria2 config has TLS cert and key paths" {
    grep -qE '^\s+cert:\s+' "$HY2_FIXTURE_DIR/config.yaml"
    grep -qE '^\s+key:\s+' "$HY2_FIXTURE_DIR/config.yaml"
}

@test "Hysteria2 config has auth password" {
    grep -qE '^\s+password:\s+\S+' "$HY2_FIXTURE_DIR/config.yaml"
}

@test "Hysteria2 config has masquerade proxy URL" {
    grep -qE '^\s+url:\s+https?://' "$HY2_FIXTURE_DIR/config.yaml"
}

@test "Hysteria2 config has obfs salamander" {
    grep -qE '^\s+type:\s+salamander' "$HY2_FIXTURE_DIR/config.yaml"
}

# ============================================================
# Cross-protocol systemd command consistency
# ============================================================

@test "All protocol deploy.sh use 'systemctl enable/restart' not bare 'service'" {
    local proto_dir="$PROJECT_ROOT/scripts/protocols"
    for deploy_script in "$proto_dir"/*/deploy.sh; do
        [ -f "$deploy_script" ] || continue
        local name
        name=$(basename "$(dirname "$deploy_script")")

        # Must NOT use bare "service <name> start" (e.g. "service nginx restart")
        # We check for lines that begin with "service" (after whitespace) followed
        # by a service name — excluding .service filenames, function defs, and systemd [Service] headers
        run bash -c 'grep -nE "^\s*service\s+" "$1" | grep -qvE "\.service|_service\(|\[Service\]|#.*service"'
    done
    # All must use systemctl enable
    for deploy_script in "$proto_dir"/*/deploy.sh; do
        [ -f "$deploy_script" ] || continue
        local name
        name=$(basename "$(dirname "$deploy_script")")
        run grep -qE 'systemctl\s+enable' "$deploy_script"
        if [ "$status" -ne 0 ]; then
            echo "# FAIL: $deploy_script lacks 'systemctl enable'" >&3
            return 1
        fi
    done
    # All must use systemctl restart (or start)
    for deploy_script in "$proto_dir"/*/deploy.sh; do
        [ -f "$deploy_script" ] || continue
        local name
        name=$(basename "$(dirname "$deploy_script")")
        run grep -qE 'systemctl\s+(restart|start)' "$deploy_script"
        if [ "$status" -ne 0 ]; then
            echo "# FAIL: $deploy_script lacks 'systemctl restart/start'" >&3
            return 1
        fi
    done
}
