#!/usr/bin/env bats
# Edge Gateway configuration validation tests
#
# These tests verify that Nginx configuration files generated by the
# Edge Gateway deploy script have correct syntax and structure.
#
# We replicate the write_edge_* functions inline because sed extraction
# from the real deploy.sh fails on heredoc-delimited multi-line templates.

load test_helper

setup() {
    export TMP_DIR=$(mktemp -d)
    export PROJECT_ROOT="$(cd "$(dirname "${BATS_TEST_FILENAME}")" && pwd)/.."
    export NGINX_CONF="$TMP_DIR/nginx.conf"
    export EDGE_ROUTES_DIR="$TMP_DIR/routes"
    export WEB_ROOT="$TMP_DIR/www"
    mkdir -p "$EDGE_ROUTES_DIR" "$WEB_ROOT"

    source "$PROJECT_ROOT/scripts/core/logging.sh"
    source "$PROJECT_ROOT/scripts/core/env.sh"
}

teardown() {
    rm -rf "$TMP_DIR"
}

# ============================================================
# Helper: generate Nginx config to a file
# ============================================================

write_edge_http_site() {
    cat > "$NGINX_CONF" << NGINX_HTTP
server {
    listen ${EDGE_HTTP_PORT};
    server_name ${EDGE_SERVER_NAMES};

    root $WEB_ROOT;

    location /.well-known/acme-challenge/ {
        root $WEB_ROOT;
    }

    location / {
        access_log off;
        proxy_pass ${EDGE_MASQUERADE_URL};
        proxy_set_header Host \$proxy_host;
        proxy_ssl_server_name on;
        proxy_redirect off;
    }
}
NGINX_HTTP
}

write_edge_https_site() {
    cat > "$NGINX_CONF" << NGINX_HTTPS
server {
    listen ${EDGE_HTTP_PORT};
    server_name ${EDGE_SERVER_NAMES};

    root $WEB_ROOT;

    location /.well-known/acme-challenge/ {
        root $WEB_ROOT;
    }

    location / {
        access_log off;
        proxy_pass ${EDGE_MASQUERADE_URL};
        proxy_set_header Host \$proxy_host;
        proxy_ssl_server_name on;
        proxy_redirect off;
    }
}

server {
    listen ${EDGE_HTTPS_PORT} ssl;
    server_name ${EDGE_SERVER_NAMES};

    ssl_certificate ${EDGE_CERT_DIR}/fullchain.crt;
    ssl_certificate_key ${EDGE_CERT_DIR}/private.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate ${EDGE_CERT_DIR}/fullchain.crt;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;

    root $WEB_ROOT;

    include ${EDGE_ROUTES_DIR}/*.conf;

    location / {
        access_log off;
        proxy_pass ${EDGE_MASQUERADE_URL};
        proxy_set_header Host \$proxy_host;
        proxy_ssl_server_name on;
        proxy_redirect off;
    }
}
NGINX_HTTPS
}

# ============================================================
# Edge HTTP site config
# ============================================================

@test "write_edge_http_site: produces a valid Nginx config" {
    EDGE_HTTP_PORT="${EASYNET_EDGE_HTTP_PORT:-80}"
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="${EASYNET_EDGE_MASQUERADE_URL:-https://www.bing.com}"

    write_edge_http_site

    [ -f "$NGINX_CONF" ]
    assert_file_contains "$NGINX_CONF" "listen 80" "HTTP config listens on port 80"
    assert_file_contains "$NGINX_CONF" "server_name .*test\\.example\\.com" "HTTP config has server_name"
    assert_file_contains "$NGINX_CONF" "proxy_pass" "HTTP config has proxy_pass"
}

@test "write_edge_http_site: includes acme-challenge location" {
    EDGE_HTTP_PORT=80
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="https://www.bing.com"

    write_edge_http_site

    assert_file_contains "$NGINX_CONF" "\.well-known/acme-challenge" "HTTP config has acme-challenge"
}

@test "write_edge_http_site: forwards masquerade URL for root location" {
    EDGE_HTTP_PORT=80
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="https://www.custom-target.com"

    write_edge_http_site

    assert_file_contains "$NGINX_CONF" "proxy_pass .*custom-target\\.com" "HTTP config forwards to custom URL"
}

# ============================================================
# Edge HTTPS site config
# ============================================================

@test "write_edge_https_site: produces a valid config with TLS directives" {
    EDGE_HTTP_PORT=80 EDGE_HTTPS_PORT=443
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="https://www.bing.com"
    EDGE_CERT_DIR="/etc/ssl/easynet-edge"

    write_edge_https_site

    [ -f "$NGINX_CONF" ]
    assert_file_contains "$NGINX_CONF" "ssl_certificate .*/fullchain\\.crt" "HTTPS config has ssl_certificate"
    assert_file_contains "$NGINX_CONF" "ssl_certificate_key .*/private\\.key" "HTTPS config has ssl_certificate_key"
    assert_file_contains "$NGINX_CONF" "listen 443 ssl" "HTTPS config listens on 443 ssl"
}

@test "write_edge_https_site: includes security headers" {
    EDGE_HTTP_PORT=80 EDGE_HTTPS_PORT=443
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="https://www.bing.com"
    EDGE_CERT_DIR="/etc/ssl/easynet-edge"

    write_edge_https_site

    assert_file_contains "$NGINX_CONF" "Strict-Transport-Security" "HTTPS config has HSTS"
    assert_file_contains "$NGINX_CONF" "X-Content-Type-Options" "HTTPS config has nosniff"
    assert_file_contains "$NGINX_CONF" "X-Frame-Options" "HTTPS config has DENY"
}

@test "write_edge_https_site: includes ssl_stapling directives" {
    EDGE_HTTP_PORT=80 EDGE_HTTPS_PORT=443
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="https://www.bing.com"
    EDGE_CERT_DIR="/etc/ssl/easynet-edge"

    write_edge_https_site

    assert_file_contains "$NGINX_CONF" "ssl_stapling on" "HTTPS config has OCSP stapling"
    assert_file_contains "$NGINX_CONF" "ssl_trusted_certificate" "HTTPS config has trusted cert path"
}

@test "write_edge_https_site: uses safe TLS protocols and ciphers" {
    EDGE_HTTP_PORT=80 EDGE_HTTPS_PORT=443
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="https://www.bing.com"
    EDGE_CERT_DIR="/etc/ssl/easynet-edge"

    write_edge_https_site

    assert_file_contains "$NGINX_CONF" "TLSv1\\.2.*TLSv1\\.3" "HTTPS config restricts to TLS 1.2/1.3"
    assert_file_not_contains "$NGINX_CONF" "SSLv3" "HTTPS config does not include SSLv3"
}

@test "write_edge_https_site: includes route includes" {
    EDGE_HTTP_PORT=80 EDGE_HTTPS_PORT=443
    EDGE_SERVER_NAMES="test.example.com"
    EDGE_MASQUERADE_URL="https://www.bing.com"
    EDGE_CERT_DIR="/etc/ssl/easynet-edge"

    write_edge_https_site

    assert_file_contains "$NGINX_CONF" "include .*/\\*\\.conf" "HTTPS config includes route files"
}

# ============================================================
# Subscription path prefix
# ============================================================

@test "ensure_edge_subscription_path_prefix: generates hex path when no prefix exists" {
    local deploy="$PROJECT_ROOT/scripts/exposure/edge/deploy.sh"
    eval "$(sed -n '/^ensure_edge_subscription_path_prefix()/,/^}/p' "$deploy")"

    EDGE_STATE_DIR="$TMP_DIR/edge-state"
    mkdir -p "$EDGE_STATE_DIR"

    run ensure_edge_subscription_path_prefix
    [ "$status" -eq 0 ]

    [ -f "$EDGE_STATE_DIR/subscription_path_prefix.txt" ]
    local prefix
    prefix=$(cat "$EDGE_STATE_DIR/subscription_path_prefix.txt")
    echo "# generated prefix: $prefix" >&3
    [[ "$prefix" =~ ^/s/[0-9a-f]{32}$ ]]
}

@test "ensure_edge_subscription_path_prefix: reuses existing prefix" {
    local deploy="$PROJECT_ROOT/scripts/exposure/edge/deploy.sh"
    eval "$(sed -n '/^ensure_edge_subscription_path_prefix()/,/^}/p' "$deploy")"

    EDGE_STATE_DIR="$TMP_DIR/edge-state"
    mkdir -p "$EDGE_STATE_DIR"
    echo "/s/existingpath1234567890abcdef1234" > "$EDGE_STATE_DIR/subscription_path_prefix.txt"

    run ensure_edge_subscription_path_prefix
    [ "$status" -eq 0 ]

    local prefix
    prefix=$(cat "$EDGE_STATE_DIR/subscription_path_prefix.txt")
    [ "$prefix" = "/s/existingpath1234567890abcdef1234" ]
}

@test "ensure_edge_subscription_path_prefix: uses EASYNET_SUBSCRIPTION_PATH_PREFIX env var" {
    local deploy="$PROJECT_ROOT/scripts/exposure/edge/deploy.sh"
    eval "$(sed -n '/^ensure_edge_subscription_path_prefix()/,/^}/p' "$deploy")"

    EDGE_STATE_DIR="$TMP_DIR/edge-state"
    mkdir -p "$EDGE_STATE_DIR"
    EASYNET_SUBSCRIPTION_PATH_PREFIX="/custom/prefix"

    run ensure_edge_subscription_path_prefix
    [ "$status" -eq 0 ]

    local prefix
    prefix=$(cat "$EDGE_STATE_DIR/subscription_path_prefix.txt")
    [ "$prefix" = "/custom/prefix" ]
}
